[package]
name = "plebfi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libtor = "46.9"
rocket = "0.5.0-rc.1"
tokio = "1.17"
torut = "0.2"
serde = "1.0"
serde_json = "1.0"
